<?php

function double_helix_menu() {
  $items = array();
  $items['double_helix'] = array(
    'title' => 'Double Helix',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('double_helix_form'),
  );
  $items['double_helix_results'] = array(
    'title' => 'Success',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'double_helix_success',
  );
  return $items;
}

function double_helix_form() {
  $form = array();
  $form['nucleotides'] = array(
    '#title' => 'Half of your DNA helix',
    '#type' => 'textfield',
    '#description' => t('Enter half of your DNA helix. I assume you know it off the top of your head.'),
    // '#element_validate' => array(''),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function find_pair($input) {
  $first_half_helix_array = str_split($input);
  $second_half_helix_array = array();

  foreach($first_half_helix_array as $nucleotide) {
    if($nucleotide == 'A') {
      array_push($second_half_helix_array, "T");
    }elseif ($nucleotide == 'T') {
      array_push($second_half_helix_array, "A");
    }elseif ($nucleotide == "C") {
      array_push($second_half_helix_array, "G");
    }elseif ($nucleotide == 'G') {
      array_push($second_half_helix_array, "C");
    }
  }
  $second_half_helix_string = implode('', $second_half_helix_array);
  return $second_half_helix_string;
}
