<?php

function double_helix_menu() {
  $items = array();
  $items['double_helix'] = array(
    'title' => 'Double Helix',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('double_helix_form'),
  );
  $items['double_helix_results'] = array(
    'title' => 'Success',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'double_helix_success',
  );
  return $items;
}

function double_helix_form() {
  $form = array();
  $form['nucleotides'] = array(
    '#title' => 'Half of your DNA helix',
    '#type' => 'textfield',
    '#description' => t('Enter half of your DNA helix. I assume you know it off the top of your head.'),
    '#element_validate' => array('element_validate_nucleotide'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function find_pair($input) {
  $first_half_helix_array = str_split($input);
  $second_half_helix_array = array();

  foreach($first_half_helix_array as $nucleotide) {
    if($nucleotide == 'A') {
      array_push($second_half_helix_array, "T");
    }elseif ($nucleotide == 'T') {
      array_push($second_half_helix_array, "A");
    }elseif ($nucleotide == "C") {
      array_push($second_half_helix_array, "G");
    }elseif ($nucleotide == 'G') {
      array_push($second_half_helix_array, "C");
    }
  }
  $second_half_helix_string = implode('', $second_half_helix_array);
  return $second_half_helix_string;
}

function double_helix_form_submit($form, &$form_state) {
  $user_nucleotides = $form_state['values']['nucleotides'];
  $result = find_pair($user_nucleotides);
  $_SESSION['first_half'] = $user_nucleotides;
  $_SESSION['second_half'] = $result;
  $form_state['redirect'] = 'double_helix_results';
}

function double_helix_success() {
  $helix_first_half = $_SESSION['first_half'];
  $helix_second_half = $_SESSION['second_half'];
  return'<p> The first half of your double helix is: ' . $helix_first_half . ' and the second half is: ' . $helix_second_half . '. </p>';
}

function element_validate_nucleotide($element) {
  $acceptable_input_array = ['A', 'T', 'C', 'G'];
  $input_check_array = str_split($element['#value']);
  foreach($input_check_array as $letter) {
    if(!in_array($letter, $acceptable_input_array)) {
      form_error($element, t("'A', 'T', 'C', and 'G' are the only valid inputs"));
    }
  }
}
