<?php

function simple_contact_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_site_form') {
  hide($form['subject']);
  hide($form['copy']);
  $form['subject']['#default_value'] = t('Feedback');
  $form['copy']['#default_value'] = 0;
  $form['name']['#default_value'] = FALSE;
  $form['mail']['#default_value'] = FALSE;
  // print '<pre>';
  // print_r($form);
  // print '</pre>';
  }
}
